---
name: "CI for commits to the main branch"
on:
  push:
    branches:
      - master
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run linting
        run: make lint
  build:
    name: Build the Docker image
    runs-on: ubuntu-latest
    needs:
      - lint
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker images
        run: make build-ci
  push:
    name: Push to Docker Hub
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push the images to Docker Hub
        run: |
          make push
